version: '3.8'  

services:
  app:
    build:
      context: ./nodejs 
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    volumes:
      - ./nodejs:/usr/src/app
    networks:
      - my-global-network
    depends_on:
      - mongo 
  mongo:
    image: mongo
    restart: always
    volumes:
     - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
     - my-global-network
volumes:
 mongo-db:
networks:
  my-global-network:
